/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as avatar from "./Avatar";
export type { avatar };
import type * as controller from "./Controller";
export type { controller };
import type * as keyCard from "./KeyCard";
export type { keyCard };
