/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IKeyCard,
  IKeyCardInterface,
} from "../../../contracts/KeyCard/IKeyCard";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IKeyCard__factory {
  static readonly abi = _abi;
  static createInterface(): IKeyCardInterface {
    return new utils.Interface(_abi) as IKeyCardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKeyCard {
    return new Contract(address, _abi, signerOrProvider) as IKeyCard;
  }
}
