/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  AvatarInternal,
  AvatarInternalInterface,
} from "../../../contracts/Avatar/AvatarInternal";

const _abi = [
  {
    inputs: [],
    name: "MintExceedsSupply",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_newMaximumTokensSet",
        type: "uint256",
      },
    ],
    name: "MaximumTokensUpdated",
    type: "event",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea2646970667358221220026c48350a1160d05f80d846a68ad5e7419415b7b7e79c3d2dc075a689c11c8064736f6c63430008110033";

type AvatarInternalConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AvatarInternalConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AvatarInternal__factory extends ContractFactory {
  constructor(...args: AvatarInternalConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<AvatarInternal> {
    return super.deploy(overrides || {}) as Promise<AvatarInternal>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): AvatarInternal {
    return super.attach(address) as AvatarInternal;
  }
  override connect(signer: Signer): AvatarInternal__factory {
    return super.connect(signer) as AvatarInternal__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AvatarInternalInterface {
    return new utils.Interface(_abi) as AvatarInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AvatarInternal {
    return new Contract(address, _abi, signerOrProvider) as AvatarInternal;
  }
}
