/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAvatar,
  IAvatarInterface,
} from "../../../contracts/Avatar/IAvatar";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_quantity",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAvatar__factory {
  static readonly abi = _abi;
  static createInterface(): IAvatarInterface {
    return new utils.Interface(_abi) as IAvatarInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAvatar {
    return new Contract(address, _abi, signerOrProvider) as IAvatar;
  }
}
