/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace IController {
  export type SaleCategoryStruct = {
    price: PromiseOrValue<BigNumberish>;
    merkleRoot: PromiseOrValue<BytesLike>;
    perWalletLimit: PromiseOrValue<BigNumberish>;
    perTransactionLimit: PromiseOrValue<BigNumberish>;
    supply: PromiseOrValue<BigNumberish>;
    tokensMinted: PromiseOrValue<BigNumberish>;
    keyCardPerAvatar: PromiseOrValue<BigNumberish>;
    startTime: PromiseOrValue<BigNumberish>;
    endTime: PromiseOrValue<BigNumberish>;
    phase: PromiseOrValue<BigNumberish>;
    paused: PromiseOrValue<boolean>;
    isDiscountEnabled: PromiseOrValue<boolean>;
  };

  export type SaleCategoryStructOutput = [
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    number,
    boolean,
    boolean
  ] & {
    price: BigNumber;
    merkleRoot: string;
    perWalletLimit: BigNumber;
    perTransactionLimit: BigNumber;
    supply: BigNumber;
    tokensMinted: BigNumber;
    keyCardPerAvatar: BigNumber;
    startTime: BigNumber;
    endTime: BigNumber;
    phase: number;
    paused: boolean;
    isDiscountEnabled: boolean;
  };
}

export interface ControllerStorageInterface extends utils.Interface {
  functions: {
    "addSale(uint96,uint96,uint256,bytes32,uint64,uint64,uint64,uint64,uint8,bool)": FunctionFragment;
    "checkDiscountCodeValidity(uint256,uint256,address,bytes)": FunctionFragment;
    "getAvatar()": FunctionFragment;
    "getKeyCard()": FunctionFragment;
    "getSaleCategory(uint256)": FunctionFragment;
    "getSaleCategoryCounter()": FunctionFragment;
    "pause()": FunctionFragment;
    "setAvatar(address)": FunctionFragment;
    "setKeyCard(address)": FunctionFragment;
    "unpause()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addSale"
      | "checkDiscountCodeValidity"
      | "getAvatar"
      | "getKeyCard"
      | "getSaleCategory"
      | "getSaleCategoryCounter"
      | "pause"
      | "setAvatar"
      | "setKeyCard"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addSale",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "checkDiscountCodeValidity",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(functionFragment: "getAvatar", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getKeyCard",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleCategory",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getSaleCategoryCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAvatar",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setKeyCard",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addSale", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkDiscountCodeValidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAvatar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getKeyCard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSaleCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSaleCategoryCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAvatar", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setKeyCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;

  events: {
    "AddedSaleCategory(uint256,uint8)": EventFragment;
    "AvatarUpdated(address,address)": EventFragment;
    "DiscountCodeApplied(uint256)": EventFragment;
    "DiscountDisabledOnSaleCategory(uint256)": EventFragment;
    "DiscountEnabledOnSaleCategory(uint256)": EventFragment;
    "DiscountSignerUpdated(address)": EventFragment;
    "KeyCardRatioUpdatedForSaleCategory(uint256,uint64)": EventFragment;
    "MemberKeyCardUpdated(address,address)": EventFragment;
    "MerkleRootUpdatedSaleCategory(uint256,bytes32)": EventFragment;
    "PerLimitUpdatedOfSaleCategory(uint256,uint64,uint64)": EventFragment;
    "PhaseChanged(uint8)": EventFragment;
    "PriceUpdatedForSaleCategory(uint256,uint256)": EventFragment;
    "SupplyUpdatedForSaleCategory(uint256,uint64)": EventFragment;
    "TimeUpdatedForSaleCategory(uint256,uint96,uint96)": EventFragment;
    "TokenToReserveUpdated(uint8,uint96)": EventFragment;
    "TokensReserved(uint8,uint96,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddedSaleCategory"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AvatarUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DiscountCodeApplied"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DiscountDisabledOnSaleCategory"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "DiscountEnabledOnSaleCategory"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DiscountSignerUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "KeyCardRatioUpdatedForSaleCategory"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MemberKeyCardUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MerkleRootUpdatedSaleCategory"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PerLimitUpdatedOfSaleCategory"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PhaseChanged"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "PriceUpdatedForSaleCategory"
  ): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SupplyUpdatedForSaleCategory"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TimeUpdatedForSaleCategory"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenToReserveUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokensReserved"): EventFragment;
}

export interface AddedSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _phase: number;
}
export type AddedSaleCategoryEvent = TypedEvent<
  [BigNumber, number],
  AddedSaleCategoryEventObject
>;

export type AddedSaleCategoryEventFilter =
  TypedEventFilter<AddedSaleCategoryEvent>;

export interface AvatarUpdatedEventObject {
  _oldAvatar: string;
  _newAvatar: string;
}
export type AvatarUpdatedEvent = TypedEvent<
  [string, string],
  AvatarUpdatedEventObject
>;

export type AvatarUpdatedEventFilter = TypedEventFilter<AvatarUpdatedEvent>;

export interface DiscountCodeAppliedEventObject {
  _discountCodeIndex: BigNumber;
}
export type DiscountCodeAppliedEvent = TypedEvent<
  [BigNumber],
  DiscountCodeAppliedEventObject
>;

export type DiscountCodeAppliedEventFilter =
  TypedEventFilter<DiscountCodeAppliedEvent>;

export interface DiscountDisabledOnSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
}
export type DiscountDisabledOnSaleCategoryEvent = TypedEvent<
  [BigNumber],
  DiscountDisabledOnSaleCategoryEventObject
>;

export type DiscountDisabledOnSaleCategoryEventFilter =
  TypedEventFilter<DiscountDisabledOnSaleCategoryEvent>;

export interface DiscountEnabledOnSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
}
export type DiscountEnabledOnSaleCategoryEvent = TypedEvent<
  [BigNumber],
  DiscountEnabledOnSaleCategoryEventObject
>;

export type DiscountEnabledOnSaleCategoryEventFilter =
  TypedEventFilter<DiscountEnabledOnSaleCategoryEvent>;

export interface DiscountSignerUpdatedEventObject {
  _newDiscountSigner: string;
}
export type DiscountSignerUpdatedEvent = TypedEvent<
  [string],
  DiscountSignerUpdatedEventObject
>;

export type DiscountSignerUpdatedEventFilter =
  TypedEventFilter<DiscountSignerUpdatedEvent>;

export interface KeyCardRatioUpdatedForSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _newKeyCardRatio: BigNumber;
}
export type KeyCardRatioUpdatedForSaleCategoryEvent = TypedEvent<
  [BigNumber, BigNumber],
  KeyCardRatioUpdatedForSaleCategoryEventObject
>;

export type KeyCardRatioUpdatedForSaleCategoryEventFilter =
  TypedEventFilter<KeyCardRatioUpdatedForSaleCategoryEvent>;

export interface MemberKeyCardUpdatedEventObject {
  _oldKeyCard: string;
  _newKeyCard: string;
}
export type MemberKeyCardUpdatedEvent = TypedEvent<
  [string, string],
  MemberKeyCardUpdatedEventObject
>;

export type MemberKeyCardUpdatedEventFilter =
  TypedEventFilter<MemberKeyCardUpdatedEvent>;

export interface MerkleRootUpdatedSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _newMerkleRoot: string;
}
export type MerkleRootUpdatedSaleCategoryEvent = TypedEvent<
  [BigNumber, string],
  MerkleRootUpdatedSaleCategoryEventObject
>;

export type MerkleRootUpdatedSaleCategoryEventFilter =
  TypedEventFilter<MerkleRootUpdatedSaleCategoryEvent>;

export interface PerLimitUpdatedOfSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _newPerTransactionLimit: BigNumber;
  _newPerWalletLimit: BigNumber;
}
export type PerLimitUpdatedOfSaleCategoryEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  PerLimitUpdatedOfSaleCategoryEventObject
>;

export type PerLimitUpdatedOfSaleCategoryEventFilter =
  TypedEventFilter<PerLimitUpdatedOfSaleCategoryEvent>;

export interface PhaseChangedEventObject {
  newPhaseId: number;
}
export type PhaseChangedEvent = TypedEvent<[number], PhaseChangedEventObject>;

export type PhaseChangedEventFilter = TypedEventFilter<PhaseChangedEvent>;

export interface PriceUpdatedForSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _newPrice: BigNumber;
}
export type PriceUpdatedForSaleCategoryEvent = TypedEvent<
  [BigNumber, BigNumber],
  PriceUpdatedForSaleCategoryEventObject
>;

export type PriceUpdatedForSaleCategoryEventFilter =
  TypedEventFilter<PriceUpdatedForSaleCategoryEvent>;

export interface SupplyUpdatedForSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _newSupplyForTheSale: BigNumber;
}
export type SupplyUpdatedForSaleCategoryEvent = TypedEvent<
  [BigNumber, BigNumber],
  SupplyUpdatedForSaleCategoryEventObject
>;

export type SupplyUpdatedForSaleCategoryEventFilter =
  TypedEventFilter<SupplyUpdatedForSaleCategoryEvent>;

export interface TimeUpdatedForSaleCategoryEventObject {
  _saleCategoryId: BigNumber;
  _newStartTime: BigNumber;
  _newEndTime: BigNumber;
}
export type TimeUpdatedForSaleCategoryEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  TimeUpdatedForSaleCategoryEventObject
>;

export type TimeUpdatedForSaleCategoryEventFilter =
  TypedEventFilter<TimeUpdatedForSaleCategoryEvent>;

export interface TokenToReserveUpdatedEventObject {
  phaseId: number;
  tokensToReserve: BigNumber;
}
export type TokenToReserveUpdatedEvent = TypedEvent<
  [number, BigNumber],
  TokenToReserveUpdatedEventObject
>;

export type TokenToReserveUpdatedEventFilter =
  TypedEventFilter<TokenToReserveUpdatedEvent>;

export interface TokensReservedEventObject {
  phaseId: number;
  numberOfTokensReserved: BigNumber;
  receiver: string;
}
export type TokensReservedEvent = TypedEvent<
  [number, BigNumber, string],
  TokensReservedEventObject
>;

export type TokensReservedEventFilter = TypedEventFilter<TokensReservedEvent>;

export interface ControllerStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ControllerStorageInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addSale(
      _startTime: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _merkleRoot: PromiseOrValue<BytesLike>,
      _perWalletLimit: PromiseOrValue<BigNumberish>,
      _perTransactionLimit: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      _keyCardPerAvatar: PromiseOrValue<BigNumberish>,
      _phase: PromiseOrValue<BigNumberish>,
      _isDiscountEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    checkDiscountCodeValidity(
      _discountIndex: PromiseOrValue<BigNumberish>,
      _discountedPrice: PromiseOrValue<BigNumberish>,
      _receiverAddress: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getAvatar(overrides?: CallOverrides): Promise<[string]>;

    getKeyCard(overrides?: CallOverrides): Promise<[string]>;

    getSaleCategory(
      _saleCategoryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[IController.SaleCategoryStructOutput]>;

    getSaleCategoryCounter(overrides?: CallOverrides): Promise<[BigNumber]>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setAvatar(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setKeyCard(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addSale(
    _startTime: PromiseOrValue<BigNumberish>,
    _endTime: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    _merkleRoot: PromiseOrValue<BytesLike>,
    _perWalletLimit: PromiseOrValue<BigNumberish>,
    _perTransactionLimit: PromiseOrValue<BigNumberish>,
    _supply: PromiseOrValue<BigNumberish>,
    _keyCardPerAvatar: PromiseOrValue<BigNumberish>,
    _phase: PromiseOrValue<BigNumberish>,
    _isDiscountEnabled: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  checkDiscountCodeValidity(
    _discountIndex: PromiseOrValue<BigNumberish>,
    _discountedPrice: PromiseOrValue<BigNumberish>,
    _receiverAddress: PromiseOrValue<string>,
    _signature: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getAvatar(overrides?: CallOverrides): Promise<string>;

  getKeyCard(overrides?: CallOverrides): Promise<string>;

  getSaleCategory(
    _saleCategoryId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<IController.SaleCategoryStructOutput>;

  getSaleCategoryCounter(overrides?: CallOverrides): Promise<BigNumber>;

  pause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setAvatar(
    arg0: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setKeyCard(
    arg0: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unpause(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addSale(
      _startTime: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _merkleRoot: PromiseOrValue<BytesLike>,
      _perWalletLimit: PromiseOrValue<BigNumberish>,
      _perTransactionLimit: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      _keyCardPerAvatar: PromiseOrValue<BigNumberish>,
      _phase: PromiseOrValue<BigNumberish>,
      _isDiscountEnabled: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    checkDiscountCodeValidity(
      _discountIndex: PromiseOrValue<BigNumberish>,
      _discountedPrice: PromiseOrValue<BigNumberish>,
      _receiverAddress: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAvatar(overrides?: CallOverrides): Promise<string>;

    getKeyCard(overrides?: CallOverrides): Promise<string>;

    getSaleCategory(
      _saleCategoryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<IController.SaleCategoryStructOutput>;

    getSaleCategoryCounter(overrides?: CallOverrides): Promise<BigNumber>;

    pause(overrides?: CallOverrides): Promise<void>;

    setAvatar(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setKeyCard(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unpause(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AddedSaleCategory(uint256,uint8)"(
      _saleCategoryId?: null,
      _phase?: null
    ): AddedSaleCategoryEventFilter;
    AddedSaleCategory(
      _saleCategoryId?: null,
      _phase?: null
    ): AddedSaleCategoryEventFilter;

    "AvatarUpdated(address,address)"(
      _oldAvatar?: null,
      _newAvatar?: null
    ): AvatarUpdatedEventFilter;
    AvatarUpdated(
      _oldAvatar?: null,
      _newAvatar?: null
    ): AvatarUpdatedEventFilter;

    "DiscountCodeApplied(uint256)"(
      _discountCodeIndex?: null
    ): DiscountCodeAppliedEventFilter;
    DiscountCodeApplied(
      _discountCodeIndex?: null
    ): DiscountCodeAppliedEventFilter;

    "DiscountDisabledOnSaleCategory(uint256)"(
      _saleCategoryId?: null
    ): DiscountDisabledOnSaleCategoryEventFilter;
    DiscountDisabledOnSaleCategory(
      _saleCategoryId?: null
    ): DiscountDisabledOnSaleCategoryEventFilter;

    "DiscountEnabledOnSaleCategory(uint256)"(
      _saleCategoryId?: null
    ): DiscountEnabledOnSaleCategoryEventFilter;
    DiscountEnabledOnSaleCategory(
      _saleCategoryId?: null
    ): DiscountEnabledOnSaleCategoryEventFilter;

    "DiscountSignerUpdated(address)"(
      _newDiscountSigner?: null
    ): DiscountSignerUpdatedEventFilter;
    DiscountSignerUpdated(
      _newDiscountSigner?: null
    ): DiscountSignerUpdatedEventFilter;

    "KeyCardRatioUpdatedForSaleCategory(uint256,uint64)"(
      _saleCategoryId?: null,
      _newKeyCardRatio?: null
    ): KeyCardRatioUpdatedForSaleCategoryEventFilter;
    KeyCardRatioUpdatedForSaleCategory(
      _saleCategoryId?: null,
      _newKeyCardRatio?: null
    ): KeyCardRatioUpdatedForSaleCategoryEventFilter;

    "MemberKeyCardUpdated(address,address)"(
      _oldKeyCard?: null,
      _newKeyCard?: null
    ): MemberKeyCardUpdatedEventFilter;
    MemberKeyCardUpdated(
      _oldKeyCard?: null,
      _newKeyCard?: null
    ): MemberKeyCardUpdatedEventFilter;

    "MerkleRootUpdatedSaleCategory(uint256,bytes32)"(
      _saleCategoryId?: null,
      _newMerkleRoot?: null
    ): MerkleRootUpdatedSaleCategoryEventFilter;
    MerkleRootUpdatedSaleCategory(
      _saleCategoryId?: null,
      _newMerkleRoot?: null
    ): MerkleRootUpdatedSaleCategoryEventFilter;

    "PerLimitUpdatedOfSaleCategory(uint256,uint64,uint64)"(
      _saleCategoryId?: null,
      _newPerTransactionLimit?: null,
      _newPerWalletLimit?: null
    ): PerLimitUpdatedOfSaleCategoryEventFilter;
    PerLimitUpdatedOfSaleCategory(
      _saleCategoryId?: null,
      _newPerTransactionLimit?: null,
      _newPerWalletLimit?: null
    ): PerLimitUpdatedOfSaleCategoryEventFilter;

    "PhaseChanged(uint8)"(newPhaseId?: null): PhaseChangedEventFilter;
    PhaseChanged(newPhaseId?: null): PhaseChangedEventFilter;

    "PriceUpdatedForSaleCategory(uint256,uint256)"(
      _saleCategoryId?: null,
      _newPrice?: null
    ): PriceUpdatedForSaleCategoryEventFilter;
    PriceUpdatedForSaleCategory(
      _saleCategoryId?: null,
      _newPrice?: null
    ): PriceUpdatedForSaleCategoryEventFilter;

    "SupplyUpdatedForSaleCategory(uint256,uint64)"(
      _saleCategoryId?: null,
      _newSupplyForTheSale?: null
    ): SupplyUpdatedForSaleCategoryEventFilter;
    SupplyUpdatedForSaleCategory(
      _saleCategoryId?: null,
      _newSupplyForTheSale?: null
    ): SupplyUpdatedForSaleCategoryEventFilter;

    "TimeUpdatedForSaleCategory(uint256,uint96,uint96)"(
      _saleCategoryId?: null,
      _newStartTime?: null,
      _newEndTime?: null
    ): TimeUpdatedForSaleCategoryEventFilter;
    TimeUpdatedForSaleCategory(
      _saleCategoryId?: null,
      _newStartTime?: null,
      _newEndTime?: null
    ): TimeUpdatedForSaleCategoryEventFilter;

    "TokenToReserveUpdated(uint8,uint96)"(
      phaseId?: null,
      tokensToReserve?: null
    ): TokenToReserveUpdatedEventFilter;
    TokenToReserveUpdated(
      phaseId?: null,
      tokensToReserve?: null
    ): TokenToReserveUpdatedEventFilter;

    "TokensReserved(uint8,uint96,address)"(
      phaseId?: null,
      numberOfTokensReserved?: null,
      receiver?: null
    ): TokensReservedEventFilter;
    TokensReserved(
      phaseId?: null,
      numberOfTokensReserved?: null,
      receiver?: null
    ): TokensReservedEventFilter;
  };

  estimateGas: {
    addSale(
      _startTime: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _merkleRoot: PromiseOrValue<BytesLike>,
      _perWalletLimit: PromiseOrValue<BigNumberish>,
      _perTransactionLimit: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      _keyCardPerAvatar: PromiseOrValue<BigNumberish>,
      _phase: PromiseOrValue<BigNumberish>,
      _isDiscountEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    checkDiscountCodeValidity(
      _discountIndex: PromiseOrValue<BigNumberish>,
      _discountedPrice: PromiseOrValue<BigNumberish>,
      _receiverAddress: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAvatar(overrides?: CallOverrides): Promise<BigNumber>;

    getKeyCard(overrides?: CallOverrides): Promise<BigNumber>;

    getSaleCategory(
      _saleCategoryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSaleCategoryCounter(overrides?: CallOverrides): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setAvatar(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setKeyCard(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addSale(
      _startTime: PromiseOrValue<BigNumberish>,
      _endTime: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      _merkleRoot: PromiseOrValue<BytesLike>,
      _perWalletLimit: PromiseOrValue<BigNumberish>,
      _perTransactionLimit: PromiseOrValue<BigNumberish>,
      _supply: PromiseOrValue<BigNumberish>,
      _keyCardPerAvatar: PromiseOrValue<BigNumberish>,
      _phase: PromiseOrValue<BigNumberish>,
      _isDiscountEnabled: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    checkDiscountCodeValidity(
      _discountIndex: PromiseOrValue<BigNumberish>,
      _discountedPrice: PromiseOrValue<BigNumberish>,
      _receiverAddress: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAvatar(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getKeyCard(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSaleCategory(
      _saleCategoryId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSaleCategoryCounter(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setAvatar(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setKeyCard(
      arg0: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
