/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Controller } from "./Controller";
export type { ControllerInternal } from "./ControllerInternal";
export type { ControllerStorage } from "./ControllerStorage";
export type { IController } from "./IController";
