/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ControllerInternal,
  ControllerInternalInterface,
} from "../../../contracts/Controller/ControllerInternal";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_oldAvatar",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_newAvatar",
        type: "address",
      },
    ],
    name: "AvatarUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_oldKeyCard",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "_newKeyCard",
        type: "address",
      },
    ],
    name: "MemberKeyCardUpdated",
    type: "event",
  },
];

export class ControllerInternal__factory {
  static readonly abi = _abi;
  static createInterface(): ControllerInternalInterface {
    return new utils.Interface(_abi) as ControllerInternalInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ControllerInternal {
    return new Contract(address, _abi, signerOrProvider) as ControllerInternal;
  }
}
