/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IController,
  IControllerInterface,
} from "../../../contracts/Controller/IController";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint96",
        name: "_startTime",
        type: "uint96",
      },
      {
        internalType: "uint96",
        name: "_endTime",
        type: "uint96",
      },
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "_merkleRoot",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "_perWalletLimit",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_perTransactionLimit",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_supply",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "_keyCardPerAvatar",
        type: "uint64",
      },
      {
        internalType: "enum IController.PHASE_ID",
        name: "_phase",
        type: "uint8",
      },
      {
        internalType: "bool",
        name: "_isDiscountEnabled",
        type: "bool",
      },
    ],
    name: "addSale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_discountIndex",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_discountedPrice",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_receiverAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_signature",
        type: "bytes",
      },
    ],
    name: "checkDiscountCodeValidity",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAvatar",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getKeyCard",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_saleCategoryId",
        type: "uint256",
      },
    ],
    name: "getSaleCategory",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "price",
            type: "uint256",
          },
          {
            internalType: "bytes32",
            name: "merkleRoot",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "perWalletLimit",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "perTransactionLimit",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supply",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "tokensMinted",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "keyCardPerAvatar",
            type: "uint64",
          },
          {
            internalType: "uint96",
            name: "startTime",
            type: "uint96",
          },
          {
            internalType: "uint96",
            name: "endTime",
            type: "uint96",
          },
          {
            internalType: "enum IController.PHASE_ID",
            name: "phase",
            type: "uint8",
          },
          {
            internalType: "bool",
            name: "paused",
            type: "bool",
          },
          {
            internalType: "bool",
            name: "isDiscountEnabled",
            type: "bool",
          },
        ],
        internalType: "struct IController.SaleCategory",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getSaleCategoryCounter",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "setAvatar",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "setKeyCard",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IController__factory {
  static readonly abi = _abi;
  static createInterface(): IControllerInterface {
    return new utils.Interface(_abi) as IControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IController {
    return new Contract(address, _abi, signerOrProvider) as IController;
  }
}
