/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Avatar } from "./Avatar";
export type { AvatarInternal } from "./AvatarInternal";
export type { AvatarStorage } from "./AvatarStorage";
export type { IAvatar } from "./IAvatar";
